spring:
  datasource:
    hikari:
      username: root
      password: root
    url: jdbc:mysql://localhost:3306/spring_boot_service
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info


