package com.spring.domain.enums;

public enum LogTags {

    PURCHASE_CREATION,
    PURCHASE_CREATION_ERROR,
    PURCHASE_ITEM_CREATION,
    PURCHASE_ITEM_CREATION_ERROR,
    PURCHASE_ITEM_FETCH_ERROR,
    USER_CREATION,
    USER_CREATION_ERROR,
    PRODUCT_CREATION,
    PRODUCT_CREATION_ERROR

}
